declare module NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_FIREBASE_DATABASE_URL: string;

    NEXT_PUBLIC_CLOUDINARY_PRESET_NAME: string;
    NEXT_PUBLIC_CLOUDINARY_API_KEY: string;
    NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: string;
    NEXT_PUBLIC_CLOUDINARY_API_SECRET: string;
  }
}
